name: Nightly LLVM Head Build
on:
  push:
    paths:
      - '**/nightly-llvm-build.yml'
  pull_request:
    branches:
      - develop
    paths:
      - '**/nightly-llvm-build.yml'
  workflow_dispatch:
  schedule:
    - cron: 45 7 * * *
# This is 7:45 AM UTC daily, late at night in the USA

# Since push and pull_request will still always be building and testing the `develop` branch,
# it only makes sense to test if this file has been changed

jobs:
  build-LLVM-Head:
    strategy:
      matrix:
        os: [macOS-11.0, macOS-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Random delay for cron job
        run: |
          delay=$(( RANDOM % 600 ))
          printf 'Delaying for %s seconds on event %s' ${delay} "${{ github.event_name }}"
          sleep ${delay}
        if: github.event_name == 'schedule'

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Uninstall all formulae
        run: brew uninstall $(brew list --formula)

      - name: Run `brew config` and `brew doctor`
        run: brew config && brew doctor

      - name: Install prerequisites
        run: brew install --HEAD --only-dependencies --keep-tmp --verbose llvm

      - name: Install and bottle LLVM
        run: brew install --HEAD --build-bottle --bottle-arch=native --keep-tmp --verbose llvm

      - name: Create bottle
        run: |
          brew bottle --verbose llvm
          mkdir bottles
          mv *.bottle.* bottles

      - name: Upload bottle
        uses: actions/upload-artifact@main
        with:
          name: bottle-${{ matrix.os }}
          path: bottles

      - name: Show linkage
        run: brew linkage --verbose llvm

      - name: Test LLVM
        run: |
          brew install gnu-sed
          gsed -i 's|\(clean_version =\).*|\1 Utils.safe_popen_read(bin/"llvm-config", "--version")[/(\d+\.?)*/]|' \
              $(brew --repository homebrew/core)/Formula/llvm.rb
          brew test --HEAD --verbose llvm

      - name: Post logs on failure
        if: failure()
        run: brew gist-logs --with-hostname --verbose llvm
