name: Test Julia
on: workflow_dispatch
jobs:
  test-julia:
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: false

      - name: Uninstall Julia cask
        if: matrix.os != 'ubuntu-latest'
        run: brew uninstall --cask --force julia

      - name: Install Julia formula
        run: brew install --formula julia

      - name: Run tests
        run: |
          JULIA="$(brew --prefix julia)/bin/julia"
          "$JULIA" -e 'include(joinpath(Sys.BINDIR, Base.DATAROOTDIR, "julia", "test", "choosetests.jl")); \
            Base.runtests(append!(choosetests()[1], ["LibGit2/online", "download"]); ncores=Sys.CPU_THREADS)'

      - run: julia -e 'Base.runtests("all"; ncores=Sys.CPU_THREADS)'
