name: Test Julia (HEAD)
on: workflow_dispatch
jobs:
  test-julia:
    strategy:
      matrix:
        os: [macos-11.0, macOS-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Uninstall Julia cask
        if: matrix.os != 'ubuntu-latest'
        run: brew uninstall --cask julia

      - name: Install Julia formula
        run: brew install --HEAD julia

      - name: Run tests
        run: |
          julia -e 'include(joinpath(Sys.BINDIR, Base.DATAROOTDIR, "julia", "test", "choosetests.jl")); \
            Base.runtests(append!(choosetests()[1], ["LibGit2/online", "download"]); ncores=Sys.CPU_THREADS)'

      # - run: julia -e 'Base.runtests("all"; ncores=Sys.CPU_THREADS)'
