name: Test Julia
on: workflow_dispatch
jobs:
  test-julia:
    strategy:
      matrix:
        os: [macos-11.0, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew install carlocab/personal/julia

      - run: $(brew --prefix julia)/bin/julia -e 'Base.runtests("all"; ncores=Sys.CPU_THREADS)'
